apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace : wso2is
  labels:
    deployment: wso2is
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: rnd-isurug-charindu
    service.beta.kubernetes.io/azure-pip-name: wso2is-central-us
spec:
  type: LoadBalancer
  selector:
    deployment: wso2is
  ports:  
  - name: servlet-http
    port: 9763
    targetPort: 9763
    protocol: TCP
  - name: servlet-https
    port: 443
    targetPort: 9443
    protocol: TCP