# Deployment config for Identity Server deployment
    [server]
    hostname = "wso2-is.trafficmanager.net"
    node_ip = "$env{NODE_IP}"
    base_path = "https://$ref{server.hostname}:${carbon.management.port}"
    force_local_cache = true

    [super_admin] 
    username = "admin"
    password = "admin"
    create_admin_account = true

    [user_store]
    type = "database_unique_id"

    [database.identity_db]
    type = "h2"
    url = "jdbc:h2:./repository/database/WSO2IDENTITY_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
    username = "wso2carbon"
    password = "wso2carbon"

    [database.shared_db]
    type = "h2"
    url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
    username = "wso2carbon"
    password = "wso2carbon"
    
    [clustering]
    membership_scheme = "kubernetes"
    domain = "wso2.carbon.domain"

    [clustering.properties]
    membershipSchemeClassName = "org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme"
    KUBERNETES_NAMESPACE = "wso2is"
    KUBERNETES_SERVICES = "identity-service"
    KUBERNETES_MASTER_SKIP_SSL_VERIFICATION = true
    USE_DNS = false

    [hazelcast]
    "hazelcast.shutdownhook.enabled" = "false"
    "hazelcast.logging.type"= "log4j2"

    [transport.http.properties]
    proxyPort = 80
    [transport.https.properties]
    proxyPort = 443

    [identity_mgt.user_self_registration]
    callback_url = "${carbon.protocol}:\\/\\/${carbon.host}\\/.*"
    
    [keystore.primary]
    file_name = "wso2carbon.jks"
    password = "wso2carbon"

    [truststore]
    file_name="client-truststore.jks"
    password="wso2carbon"
    type="JKS"

    [account_recovery.endpoint.auth]
    hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

    [identity.auth_framework.endpoint]
    app_password= "dashboard"

    [cors]
    allow_generic_http_requests = true
    allow_any_origin = true
    allow_subdomains = true
    supported_methods = [
    "GET",
    "POST",
    "HEAD",
    "OPTIONS"
    ]
    support_any_header = true
    supported_headers = []
    exposed_headers = []
    supports_credentials = true
    max_age = 3600
    tag_requests = false

    [[event_listener]]
    id = "custom-user-operation-event-listener"
    type = "org.wso2.carbon.user.core.listener.UserOperationEventListener"
    name = "org.wso2.custom.user.operation.event.listener.CustomUserOperationEventListener"
    order = 9000
    enable = true
    
    # from configmap
