apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.depName }}
  namespace: wso2is
  labels:
    deployment: wso2is-hdr # Labels for the deployment itself
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: wso2is-hdr  # Selector labels to match labels in the pod template
  template:
    metadata:
      labels:
        deployment: wso2is-hdr  # Labels applied to pods created by this template
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /carbon/admin/login.jsp
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.wso2.deployment.wso2is.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.wso2is.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /api/health-check/v1.0/health
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.wso2.deployment.wso2is.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.wso2is.readinessProbe.periodSeconds }}
          ports:
            - containerPort: 9443
            - containerPort: 4000
            - containerPort: 9763
            - containerPort: 3306
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts: 
            - name: identity-server-conf-read-only-hdr
              mountPath: /home/wso2carbon/wso2is-7.0.0/repository/conf/deployment.toml
              subPath: deployment.toml

      volumes:
        - name: identity-server-conf-read-only-hdr
          configMap:
            name: identity-server-conf-read-only-hdr
      serviceAccountName: is-service-account