isReadOnly: true
depName: is-deployment
serName: is-service
ingName: is-ingress
appName: is
image:
  name: acrasgardeomainrnd001.azurecr.io/is7.0
  tag: rolesync

# Number of deployment replicas
replicas: 1

wso2:
  deployment:
    wso2is: 
      config: true
      
      # Kubernetes Probes
      # Startup probe executed prior to Liveness Probe taking over
      startupProbe:
        # Number of seconds after the container has started before startup probes are initiated
        initialDelaySeconds: 60
        # How often (in seconds) to perform the probe
        periodSeconds: 5
        # Number of attempts
        failureThreshold: 30
      # Indicates whether the container is running
      livenessProbe:
        # Number of seconds after the container has started before liveness probes are initiated
        initialDelaySeconds: 60
        # How often (in seconds) to perform the probe
        periodSeconds: 10
        # Number of attempts
        failureThreshold: 30
      # Indicates whether the container is ready to service requests
      readinessProbe:
        # Number of seconds after the container has started before readiness probes are initiated
        initialDelaySeconds: 60
        # How often (in seconds) to perform the probe
        periodSeconds: 10